//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace runic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("runic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start = trim @(rule, newlines, 1, 0) final_trim
        ///none = /&amp;*/
        ///final_trim = /\s*$/
        ///newlines = /(\s*\n)+\s*/
        ///id = /[\$a-zA-Z0-9_]+/
        ///trim = /\s*/
        ///option_separator = trim &quot;|&quot; trim
        ///string = (&apos;&quot;&apos; /[^&quot;]*/ &apos;&quot;&apos;) | (&quot;&apos;&quot; /[^&apos;]*/ &quot;&apos;&quot;)
        ///regex = &quot;/&quot; /[^\/]+/ &quot;/&quot;
        ///group = &quot;(&quot; trim @(option, option_separator, 2, 0) trim &quot;)&quot;
        ///option = id | string | regex | group
        ///comma = /\s*,\s*/
        ///attribute = /\w+/
        ///attributes = &quot;(&quot; @(attribute, comma, 0, 0) &quot;)&quot;
        ///rule = id @(attributes, none, 0, 1) trim &quot;=&quot; trim @(option, option_separ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lexer_grammar {
            get {
                return ResourceManager.GetString("lexer_grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start = trim @(rule, newlines, 1, 0) final_trim
        ///final_trim = /\s*$/
        ///newlines = /(\s*\n)+\s*/
        ///id = /[\$a-zA-Z0-9_]+/
        ///trim = /\s*/
        ///or = trim &quot;|&quot; trim
        ///spaces = /[ \t]+/
        ///comma = /\s*,\s*/
        ///repetition = &quot;@(&quot; trim @(id, comma, 3, 4) trim &quot;)&quot;
        ///option = id | repetition
        ///group = @(option, or, 0, 0) | @(option, spaces, 0, 0)
        ///rule = id trim &quot;=&quot; trim group.
        /// </summary>
        internal static string parser_grammar {
            get {
                return ResourceManager.GetString("parser_grammar", resourceCulture);
            }
        }
    }
}
